// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBec8kmFRnNOlBIwdOSejy7oeYyofil6PY',
    appId: '1:983702128195:web:cf9818eff030192d6176f6',
    messagingSenderId: '983702128195',
    projectId: 'agrifresh-9e582',
    authDomain: 'agrifresh-9e582.firebaseapp.com',
    storageBucket: 'agrifresh-9e582.firebasestorage.app',
    measurementId: 'G-WHXG8LFZBS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUoxEIuKM60lcnILJdtEliHz6HJEcyD-Y',
    appId: '1:983702128195:android:414aa1a4a4d9ad476176f6',
    messagingSenderId: '983702128195',
    projectId: 'agrifresh-9e582',
    storageBucket: 'agrifresh-9e582.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiu9bXGyHN3t9Uy72Pof-EwPMpx1MDRdQ',
    appId: '1:983702128195:ios:d35314419d77b4a26176f6',
    messagingSenderId: '983702128195',
    projectId: 'agrifresh-9e582',
    storageBucket: 'agrifresh-9e582.firebasestorage.app',
    iosBundleId: 'com.example.agrifresh',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiu9bXGyHN3t9Uy72Pof-EwPMpx1MDRdQ',
    appId: '1:983702128195:ios:d35314419d77b4a26176f6',
    messagingSenderId: '983702128195',
    projectId: 'agrifresh-9e582',
    storageBucket: 'agrifresh-9e582.firebasestorage.app',
    iosBundleId: 'com.example.agrifresh',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBec8kmFRnNOlBIwdOSejy7oeYyofil6PY',
    appId: '1:983702128195:web:33d6ff9e00e587a06176f6',
    messagingSenderId: '983702128195',
    projectId: 'agrifresh-9e582',
    authDomain: 'agrifresh-9e582.firebaseapp.com',
    storageBucket: 'agrifresh-9e582.firebasestorage.app',
    measurementId: 'G-FHPDTZL97D',
  );

}